development:
  adapter: postgresql
  database: tatra_sbb_development
  encoding: unicode
  username: postgres
  password: secret
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: tatra_sbb_test
  encoding: unicode
  username: postgres
  password: secret
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: tatra_sbb_production
  encoding: unicode
  username: postgres
  password: secret
  host: localhost
  port: 5432
